name: Build The Program

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Add MSBuild to path
      uses: microsoft/setup-msbuild@v1.3

    - name: Download and Install DirectX SDK (Fast Link)
      run: |
        Invoke-WebRequest -Uri "https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe" -OutFile "DXSDK.exe"
        Start-Process -FilePath "DXSDK.exe" -ArgumentList "/S" -Wait

    - name: Build the solution
      run: msbuild sakura.sln /p:Configuration=Release /p:Platform=x86

    - name: Upload the final program
      uses: actions/upload-artifact@v4
      with:
        name: Sakura-Program
        path: Release/sakura.exe
